/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.glb -T --shadows
Author: tamminen (https://sketchfab.com/tamminen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/exoplanet-sg10446623-128ba361498049e9b12baede75bf7b5a
Title: Exoplanet SG10446623
*/

import React, { useRef, FC } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GroupProps } from "react-three-fiber";

export const ExoPlanet: FC<GroupProps> = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/exoplanet_sg10446623/scene-transformed.glb"
  ) as any;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group as any} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Plane_1">
            <mesh
              name="Object_6"
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.lines}
            />
          </group>
        </group>
        <mesh
          name="Object_4"
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/exoplanet_sg10446623/scene-transformed.glb");
