/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf -T --shadows
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jupiter-e00d35ab713a44dfb0a7450a79a6dd80
Title: Jupiter
*/

import React, { FC, forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "react-three-fiber";
import { Group } from "three";

export const Jupiter = forwardRef<Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/jupiter/scene-transformed.glb"
  ) as any;
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Jupiter_Planeta_0.geometry}
        material={materials.Planeta}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pierscien_Pierscien_0.geometry}
        material={materials.Pierscien}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
});

useGLTF.preload("/models/jupiter/scene-transformed.glb");
