/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.glb --shadows
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React, { useRef, forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";
import { GroupProps } from "react-three-fiber";

export const MilkyWay = forwardRef<Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF("/models/space/scene.glb") as any;
  return (
    <group {...props} dispose={null} ref={ref}>
      <points
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.013}
      />
      {props.children}
    </group>
  );
});

useGLTF.preload("/models/space/scene.glb");
