/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf -T --shadows
Author: Aksin Leon (https://sketchfab.com/leonimation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neptune-90a14e75dfa1473480d08156985ad8a1
Title: Neptune
*/

//

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";
import { GroupProps } from "react-three-fiber";

export const Neptune = forwardRef<Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/neptune/scene-transformed.glb"
  ) as any;
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.aiStandardSurface4SG}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
});

useGLTF.preload("/models/neptune/scene-transformed.glb");
