/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.glb -T --shadows
Author: wardd (https://sketchfab.com/wardd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planet-ship-8225140e9f0b400991774b8403e5ad0e
Title: Planet Ship
*/

import React, { useRef, forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "react-three-fiber";
import { Group } from "three";

export const PlanetShip = forwardRef<Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/planet_ship/scene-transformed.glb"
  ) as any;
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Habitats_Habitats_0.geometry}
        material={materials.Habitats}
        position={[0, -1917.475, 11871.402]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Beams_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI, 0, Math.PI / 2]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EntryRings_GuideMaterial_0.geometry}
        material={materials.GuideMaterial}
        position={[0, 0, 7983.879]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AtmosphereWall_AtmosphereWall_0.geometry}
        material={materials.AtmosphereWall}
        position={[0, 0, 5197.701]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mirrors_Structure_0.geometry}
        material={materials.Structure}
        position={[0, 0, 5328.472]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mirrors_MIrror_0.geometry}
        material={materials.MIrror}
        position={[0, 0, 5328.472]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PlanetShip_PlanetSurface_0.geometry}
        material={materials.PlanetSurface}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
});
useGLTF.preload("/models/planet_ship/scene-transformed.glb");
