/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf -T --shadows
Author: PounUP (https://sketchfab.com/PounUP)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/planet-0104234961624b7aa0cb85d03161babe
Title: Planet
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";
import { GroupProps } from "react-three-fiber";

export const Planet = forwardRef<Group, GroupProps>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/planet/scene-transformed.glb"
  ) as any;
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.COMBINE_LP_LAM_0.geometry}
        material={materials.material}
        position={[-1.334, -0.782, 1.171]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.COMBINE_LP_1_0.geometry}
        material={materials.material_1}
        position={[-1.334, -0.782, 1.171]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.COMBINE_LP_2_0.geometry}
        material={materials.material_2}
        position={[-1.334, -0.782, 1.171]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
});

useGLTF.preload("/models/planet/scene-transformed.glb");
