/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf -T --shadows
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-9ef1c68fbb944147bcfcc891d3912645
Title: Sun
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Group } from "three";
import { GroupProps } from "react-three-fiber";

export const Sun = forwardRef<Group, GroupProps>((props, ref) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/sun/scene-transformed.glb"
  ) as any;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="UnstableStarCore" rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              name="UnstableStarCore_1_0"
              castShadow
              receiveShadow
              geometry={nodes.UnstableStarCore_1_0.geometry}
              material={materials.material}
            />
          </group>
          <group
            name="UnstableStarref"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.01}
          >
            <mesh
              name="UnstableStarref_2_0"
              castShadow
              receiveShadow
              geometry={nodes.UnstableStarref_2_0.geometry}
              material={materials.material_1}
            />
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/models/sun/scene-transformed.glb");
